### PR TITLE
Stages

### PR DESCRIPTION
**Pull request by LegitSoulja**
**Do Not Merge/Close Until Tasks Below Is Complete..**

Names in parentheses '()' are jobs taken by.

- [ ] Re-write how cells works. skins,names(text), cells in general. (LegitSoulja)
- [ ] Work on PIXI canvas, containers, and drawings (LegitSoulja)

- [ ] Re-write Physics, and main game core (fill in position)
- [ ] Finish SocketHandler (fill in position)

- [ ] Clean graphical site UI, using (sass), and SVG? (LegitSoulja)
- [ ] Site authentications, levels, coins, player stats? (LegitSoulja)

Since I know some people wants a client of their own, Iframes will be allowed, however I'm thinking of making it so that people can modify the client using server configurations/side along code.

**Last stage, with unknown tasks for now**

### CODE REVIEW

**Comment by LegitSoulja** [comment]
@Andrews54757 anything in particular you would like to assist on?

**Comment by FantasyIsBae** [comment]
@LegitSoulja @SharkFinPro is a fish ... Get it ?

**Comment by Andrews54757** [comment]
@LegitSoulja Told ya, this is not private at all

**Comment by LegitSoulja** [comment]
@Andrews54757 he always stalks my account. 

And I know this isn't private. Did you like not read anything I've said? Should I just delete this and continue with my life?

Just let me know what I should do.

**Comment by Andrews54757** [comment]
@LegitSoulja I did not read about what you said. I cant, the issues section is gone.

**Comment by LegitSoulja** [comment]
@Andrews54757 Open them, if possible. Just close it back. I was hoping you read that, or the alerts Atleast. I closed it in a hurry cause I  didn't want people searching accidentally finding this, or see the information I posted about it.

**Comment by LegitSoulja** [comment]
And sorry @FantasyIsBae, this isn't an open public place for your to be posting.

**Comment by Andrews54757** [comment]
@LegitSoulja I cant, only the owner can change the settings

**Comment by LegitSoulja** [comment]
@Andrews54757 i got it then.

**Comment by LegitSoulja** [comment]
I might move this to another group on github, instead of my personal repo's

**Comment by FantasyIsBae** [comment]
@LegitSoulja Ok no probs (Delete this)

**Comment by Andrews54757** [comment]
@LegitSoulja How about bitbucket, they have free private repos

**Comment by LegitSoulja** [comment]
@Andrews54757 sure, I guess, wanna set it up?

**Comment by LegitSoulja** [comment]
You have this https://bitbucket.org/ajsdevelopment

Create oac and invite me

**Comment by Andrews54757** [comment]
@LegitSoulja I never created that

**Comment by Andrews54757** [comment]
@LegitSoulja Are you buffalo wild wings?

**Comment by LegitSoulja** [comment]
@Andrews54757 lol yes, that may be me.

**Comment by Andrews54757** [comment]
Sent it to you

**Comment by LegitSoulja** [comment]
I guess I'm in.

**Comment by LegitSoulja** [comment]
@Andrews5475 but does it even matter? I put this `here` where I know we all publiclly place our work, and etc.

Now bitbucket will be the last place on earth you'll ever go now without a reason. Am I wrong?

Besides, what can people possible do with this? Let's add an encrypted file that loads our libraries with security as we normally put and done.

**Comment by LegitSoulja** [comment]
Note* This is not an OA client, this is an Agario Clone remake. As of now, OA is built upon this client, so for now with my less experience with canvas, I'll make this client based on the other, but more efficient.

Then, the things you've implemented for OA, won't be added here. Only things I've added for now was your player object and binreader. Once the base is done, we will remove it from here and continue working on it privately. That was ideal.

**Comment by LegitSoulja** [comment]
I was also thinking, how will it be possible to send test data to simulate a game, for client Dev purposes. But, it's not really a problem. We'll just have loads of stuff to fix at the end.

**Comment by LegitSoulja** [comment]
@Andrews54757 btw, I dislike bitbucket. We can work like this, I promise that it'll be private only if we don't use terms as  c l i e n t, and O p e n A g a r.

Otherwise, I'll secure this. I got a perfect example of how.

**Pull request merged**
